### ISSUE TITLE
Run OpenWakeWord on external server

### ISSUE THREAD

**Issue by theglus** [theglus/Homelab-Docker-Compose#70]
# Requirements
```
name: <your project name>
services:
    wyoming-openwakeword:
        stdin_open: true
        tty: true
        ports:
            - 10400:10400
        image: rhasspy/wyoming-openwakeword
        command: --preload-model 'ok_nabu'
```
# Resources 
* [GH Repo](https://github.com/rhasspy/wyoming-openwakeword)
* [Example Config](https://community.home-assistant.io/t/openwakeword-docker/626131/5)
* [Home-Assistant in Docker](https://github.com/Fraddles/Home-Automation/tree/main/Home-Assistant)
